### ISSUE TITLE
itunes

### ISSUE THREAD

**Issue by despoinamusica39** [MalgAmoe/MuzBrowz#6]
hello!!!pleaseeeeeeeeee can you upload all the code complete for using?I have no idea from programming!!!I AM BEGGING YOU...or at least one web link?

**Comment by MalgAmoe** [comment]
> 
> 
> hello!!!pleaseeeeeeeeee can you upload all the code complete for using?I have no idea from programming!!!I AM BEGGING YOU...or at least one web link?

Hi, that was some demo for a job interview.
All the code is there, but there is not much to do with this stuff to be honest.
